import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: ['nextjs', 'react', 'typescript', 'unicorn', 'import', 'jsx-a11y'],
  env: {
    browser: true,
    node: true,
  },
  categories: {
    correctness: 'error',
  },
  extends: [],
  ignorePatterns: [
    // Ignore generated shadcn components
    'components/ui/**/*',

    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by @serwist/next at build time, not source.
    'public/sw.js',
  ],
})
